'use strict';

/*
  Reglas comerciales de promociones de proveedor.
  No proceden de SAP. Se mantienen como configuración fija de la app.

  Fatro: tarifa de Oferta Distribuidor facilitada por PROVESA y tratada
  como vigente hasta que se sustituya por una nueva tarifa.
  La referencia se cruza por código de catálogo del proveedor.
*/
window.PROVESA_PROMOTIONS = [
  {"supplierMatch":"fatro","supplierCatalog":"1","minDiscountQty":50.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Tsefalen 1.000 mg (9 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"4","minDiscountQty":50.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Propancat 2 cdos."},
  {"supplierMatch":"fatro","supplierCatalog":"5","minDiscountQty":30.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Bimodula 20 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"9","minDiscountQty":50.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Leish-Tabs (100 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5030","minDiscountQty":25.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Deyanil Retard 10 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5031","minDiscountQty":56.0,"discountPct":4.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Deyanil Retard 50 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5081","minDiscountQty":30.0,"discountPct":4.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Eupen Plus 100 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5274","minDiscountQty":22.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Vetramil Pomada  30 g"},
  {"supplierMatch":"fatro","supplierCatalog":"5275","minDiscountQty":6.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Vetramil Spray   100 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5293","minDiscountQty":16.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Lactofin 3 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5294","minDiscountQty":16.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Lactofin 7 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5295","minDiscountQty":16.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Lactofin 15 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5302","minDiscountQty":60.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Flee Spray  400 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5308","minDiscountQty":15.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Prednisolona inyectable (10 ml)"},
  {"supplierMatch":"fatro","supplierCatalog":"5314","minDiscountQty":5.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Vetramil Pomada  180 g"},
  {"supplierMatch":"fatro","supplierCatalog":"5327","minDiscountQty":9.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Tsefalen 500 mg (108 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5328","minDiscountQty":8.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Tsefalen 1.000 mg (104 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5335","minDiscountQty":9.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Marbovet 20 mg (100 cdos.)"},
  {"supplierMatch":"fatro","supplierCatalog":"5336","minDiscountQty":9.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Marbovet 80 mg (100 cdos.)"},
  {"supplierMatch":"fatro","supplierCatalog":"5352","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Rheumocam  1 mg (100 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5353","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Rheumocam  2,5 mg (100 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5354","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Privaprol 1 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5355","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Privaprol 2 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5376","minDiscountQty":16.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Continenza  50 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5393","minDiscountQty":30.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Propancat 24 cdos."},
  {"supplierMatch":"fatro","supplierCatalog":"5401","minDiscountQty":40.0,"discountPct":25.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Dormisan 10 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5409","minDiscountQty":48.0,"discountPct":12.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Isoflurin 250 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5410","minDiscountQty":120.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Akiball (+25%)"},
  {"supplierMatch":"fatro","supplierCatalog":"5411","minDiscountQty":12.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Aceprovet Gotas 20 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5417","minDiscountQty":20.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Reverse 10 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5418","minDiscountQty":12.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Vetramil 5 pads (10x10)"},
  {"supplierMatch":"fatro","supplierCatalog":"5423","minDiscountQty":34.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Antishmania 10 x 5 ml."},
  {"supplierMatch":"fatro","supplierCatalog":"5446","minDiscountQty":35.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Energel (+25%)"},
  {"supplierMatch":"fatro","supplierCatalog":"5449","minDiscountQty":30.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Tenicipen 10 cdos."},
  {"supplierMatch":"fatro","supplierCatalog":"5450","minDiscountQty":12.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Tenicipen 50 cdos."},
  {"supplierMatch":"fatro","supplierCatalog":"5451","minDiscountQty":3.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Tenicipen 1.000 cdos."},
  {"supplierMatch":"fatro","supplierCatalog":"5460","minDiscountQty":56.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"OftalmoVit A (5 g)"},
  {"supplierMatch":"fatro","supplierCatalog":"5461","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Prinovox Gato pequeño (0,4x6)"},
  {"supplierMatch":"fatro","supplierCatalog":"5462","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Prinovox Gato grande (0,8x6)"},
  {"supplierMatch":"fatro","supplierCatalog":"5471","minDiscountQty":35.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Euthoxin 50%"},
  {"supplierMatch":"fatro","supplierCatalog":"5485","minDiscountQty":20.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Popandog 200 cdos"},
  {"supplierMatch":"fatro","supplierCatalog":"5486","minDiscountQty":80.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Rheumocam oral perros 15 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5487","minDiscountQty":25.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Rheumocam oral perros 42 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5488","minDiscountQty":50.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Rheumocam oral gatos 10 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5491","minDiscountQty":56.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Canidolor 5 mg 20 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5492","minDiscountQty":12.0,"discountPct":12.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Afilaria 3,4 mg/ml (17 ml.)"},
  {"supplierMatch":"fatro","supplierCatalog":"5495","minDiscountQty":48.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Cardinefril 20 mg (14 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5497","minDiscountQty":25.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Liverfine 50 ml."},
  {"supplierMatch":"fatro","supplierCatalog":"5499","minDiscountQty":30.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Semelcef 200 mg (10 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5500","minDiscountQty":9.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Semelcef 200 mg (100 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5501","minDiscountQty":20.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Semelcef 1000 mg (6 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5504","minDiscountQty":120.0,"discountPct":4.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Alutopic spray 200 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5506","minDiscountQty":120.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Triderm 30 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5507","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"FiproSmet 0,50 ml gatos (6 pip)"},
  {"supplierMatch":"fatro","supplierCatalog":"5508","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"FiproSmet 0,67 ml perro S (6 pip)"},
  {"supplierMatch":"fatro","supplierCatalog":"5509","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"FiproSmet 1,34 ml perro M (6 pip)"},
  {"supplierMatch":"fatro","supplierCatalog":"5510","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"FiproSmet 2,68 ml perro L (6 pip)"},
  {"supplierMatch":"fatro","supplierCatalog":"5511","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Chanhold 15 mg perro/gato XS (3 pip)"},
  {"supplierMatch":"fatro","supplierCatalog":"5512","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Chanhold 30 mg perro S (3 pip)"},
  {"supplierMatch":"fatro","supplierCatalog":"5513","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Chanhold 45 mg gato L (3 pip)"},
  {"supplierMatch":"fatro","supplierCatalog":"5514","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Chanhold 60 mg perro M (3 pip)"},
  {"supplierMatch":"fatro","supplierCatalog":"5515","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Chanhold 120 mg perro L (3 pip)"},
  {"supplierMatch":"fatro","supplierCatalog":"5516","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Chanhold 240 mg perro XL (3 pip)"},
  {"supplierMatch":"fatro","supplierCatalog":"5522","minDiscountQty":40.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Lagripets 15 ml."},
  {"supplierMatch":"fatro","supplierCatalog":"5525","minDiscountQty":10.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Tsefalen 50 mg SO"},
  {"supplierMatch":"fatro","supplierCatalog":"5531","minDiscountQty":120.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"EupenClav 50 (10 cdos.)"},
  {"supplierMatch":"fatro","supplierCatalog":"5532","minDiscountQty":120.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"EupenClav 250 (10 cdos.)"},
  {"supplierMatch":"fatro","supplierCatalog":"5533","minDiscountQty":120.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"EupenClav 500 (10 cdos.)"},
  {"supplierMatch":"fatro","supplierCatalog":"5548","minDiscountQty":6.0,"discountPct":4.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Afilaria 3,4 mg/ml (5,67 ml.)"},
  {"supplierMatch":"fatro","supplierCatalog":"5549","minDiscountQty":40.0,"discountPct":12.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Ketabel 10 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5550","minDiscountQty":20.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Keyvit 14 cdos."},
  {"supplierMatch":"fatro","supplierCatalog":"5558","minDiscountQty":28.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Aticare (100 g)"},
  {"supplierMatch":"fatro","supplierCatalog":"5559","minDiscountQty":12.0,"discountPct":12.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Sevohale 250 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5560","minDiscountQty":40.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"AloeOtovet 100 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5561","minDiscountQty":9.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"EupenClav 50 (100 cdos)."},
  {"supplierMatch":"fatro","supplierCatalog":"5562","minDiscountQty":9.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"EupenClav 250 (100 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5563","minDiscountQty":9.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"EupenClav 500 (100 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5564","minDiscountQty":126.0,"discountPct":25.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Otisur 15 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5565","minDiscountQty":10.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Vetramil Auris 50 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5566","minDiscountQty":20.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Vetramil cera podal 120 g"},
  {"supplierMatch":"fatro","supplierCatalog":"5568","minDiscountQty":30.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Prednisolona 5 mg (20 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5574","minDiscountQty":30.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Prednisolona 20 mg (20 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5575","minDiscountQty":6.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Caniliver comprimidos (32 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5576","minDiscountQty":6.0,"discountPct":25.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Caniliver pasta (2 jeringas)"},
  {"supplierMatch":"fatro","supplierCatalog":"5577","minDiscountQty":6.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"CL-exidin 4% Champú  (200 ml)"},
  {"supplierMatch":"fatro","supplierCatalog":"5578","minDiscountQty":6.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"CL-exidin 4% Spray  (200 ml)"},
  {"supplierMatch":"fatro","supplierCatalog":"5579","minDiscountQty":12.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"CL-Otovet  (100 ml)"},
  {"supplierMatch":"fatro","supplierCatalog":"5580","minDiscountQty":18.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Dentaldine  (30 ml)"},
  {"supplierMatch":"fatro","supplierCatalog":"5586","minDiscountQty":12.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Semelcef 1000 mg (60 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5587","minDiscountQty":48.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Oftalmovet colirio (10 ml)"},
  {"supplierMatch":"fatro","supplierCatalog":"5588","minDiscountQty":6.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Oftalmoklear 50 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5589","minDiscountQty":9.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Prednisolona 5 mg (100 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5590","minDiscountQty":9.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Prednisolona 20 mg (100 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5592","minDiscountQty":12.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Cani Tabs (60 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5599","minDiscountQty":48.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Lidobel 100 ml."},
  {"supplierMatch":"fatro","supplierCatalog":"5610","minDiscountQty":40.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Popandog 10 cdos"},
  {"supplierMatch":"fatro","supplierCatalog":"5613","minDiscountQty":18.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Fatrobendan 1,25 mg (100 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5614","minDiscountQty":18.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Fatrobendan 5 mg (100 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5615","minDiscountQty":15.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Fatrobendan 10 mg (100 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5617","minDiscountQty":96.0,"discountPct":12.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Gastrocare gel 20 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5618","minDiscountQty":70.0,"discountPct":12.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Gastrocare gel 50 ml"},
  {"supplierMatch":"fatro","supplierCatalog":"5620","minDiscountQty":18.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Fatrobendan 5 mg (50 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5621","minDiscountQty":15.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Fatrobendan 10 mg (50 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5622","minDiscountQty":35.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Duecoxin 6 mg (10 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5623","minDiscountQty":35.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Duecoxin 10 mg (10 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5624","minDiscountQty":9.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Duecoxin 40 mg (10 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5625","minDiscountQty":20.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Duecoxin 6 mg (30 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5626","minDiscountQty":20.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Duecoxin 10 mg (30 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5627","minDiscountQty":9.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Duecoxin 40 mg (30 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5628","minDiscountQty":9.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Duecoxin 6 mg (100 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5629","minDiscountQty":9.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Duecoxin 10 mg (100 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5630","minDiscountQty":9.0,"discountPct":8.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Duecoxin 40 mg (100 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5631","minDiscountQty":90.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Tsefalen 500 mg (12 cdos)"},
  {"supplierMatch":"fatro","supplierCatalog":"5633","minDiscountQty":60.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Marbovet 20 mg (10 cdos.)"},
  {"supplierMatch":"fatro","supplierCatalog":"5634","minDiscountQty":60.0,"discountPct":15.0,"promoUnitPrice":null,"label":"Fatro · Oferta distribuidor","note":"Marbovet 80 mg (10 cdos.)"},
];
